---
- name: Ensure packahe repositroy is up-to-date.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - openssl
      - htop
      - ldnsutils
      - curl
      - wget
    state: present