---
all:
  vars:
    ansible_connection: ssh
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:
    cloud-dev:
      hosts:
        cloud-dev.cloud-dev.gcp.uweeisele.dev:

    dev:
      children:
       cloud-dev:

    docker:
      children:
       cloud-dev: